### PR TITLE
Add Smash DI support

### PR DESCRIPTION
**Pull request by XeSquirmy**
A lot can be optimized/fixed so far, but I think it's ready to be merged to the main project. It's funny/sick to see the cpu look like it's teleporting :p

### CODE REVIEW

**Comment by altf4** [comment]
This looks really good, thank you! I have just a couple bits of feedback before I pull it in:

1) Remove the debug prints in  Chains/SmashDI.cpp

2) This code:

```
        if(m_isFacingRightP1 == true)
        {
            CreateChain2(SmashDI, m_isFacingRightP1);
            m_chain->PressButtons();
        }
        if(m_isFacingRightP1 == false)
        {
            CreateChain2(SmashDI, m_isFacingRightP1);
            m_chain->PressButtons();
        }
```

Is logically equivalent to just:

```
            CreateChain2(SmashDI, m_isFacingRightP1);
            m_chain->PressButtons();
```

**Comment by XeSquirmy** [comment]
Haha, oops, didn't realise that I screwed up that badly, and sorry about the debug outputs, I forgot to remove it before I did the pull request. Thanks for the feedback, I really appreciate it.

**Comment by XeSquirmy** [comment]
Alrighty, I cleaned it up a little, sorry for all the pushes to my branch, I'm a terrible programmer :p

**Comment by altf4** [comment]
That looks good. I squashed your commits down to one (you should do that in the future, but it's not a big deal) and pushed it in.

I think there's some improvements to be made, but I'll make a separate Issue for them. Good work and thanks for the contribution!

**Pull request closed without merging**
